language: node_js
node_js:
- '6'
install: npm install
before_script: npm run dist
script: npm test
before_deploy: echo "All unit tests pass. Launching build on AWS EB."
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: sfr-front-end
  env: rnw-front-end-development
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: rnw-front-end-development
  on:
    repo: NYPL/sfr-bookfinder-front-end
    branch: development
env:
  global:
  - secure: sBbLIPtXIpRUFo7PBduT8aQocYts2MTlBSKcCr/1WGGAoih3lEkTDPJkiGxaF6vqCCdfkBLPIECzYbiH49ZA6HrR/nnKVsvFbTAc5MQkCrPyipEXy27/urohzQDK1tH0wmr6Xz1Of80RwO4/viuX/pjRXwvbkw+jOO0+2J6JlLTxyNwhIn9m+id7Ja2sPB35ON+c/4X0r0bv4jMZGLg9IlC89N7q7UNdRXtpVeBTWJX//ZCEHGH1ZKqWOkC4GaWqXDDDFL75iRomkQ1akaYbFVWOVweLC1JmPXDgnhbbs7KB1kremausb/c1GhqQ1RMp5hsZCQ5ATP1pYlulo039/pRwSOGZ8so1q6KUefsU+X7RIsZ86vDU3mjIzI3URZjzUQlKo5CFdqWFULw0rOlBHPkgMLBtTgKBAe97Wx3wQBN3sm+yKoIP0GntLhCTxD4GEd1Bn7ccq+0WjGlzlLJYq1YnWoF9p/mHmWL49e6Vhn1U+MD143m4mGxUC1MYosBhm8EzT5x1vowleqvhOKmp3x3fXCfE98A/UfWyUHDBoFof2Bo5v+Y+wgAWX4+lDro0WpKZA/jPvOROnoiX8mwUS9xdOpoEu75lNg6LLcSBqjFPxcG0d5qK4uAdzpK15TS8cgfcttH2V3ZfPPPaBlSN8H+j2MfxuuvYMYca6ftSb4I=
  - secure: zcB+zqjBkv9Y2YHU3PgJ7xmWvL2q53g1zbZvmBVvLv0eEfqLr71Ca30oda0FsBLdQ0oXo4So0shBh5AME38x6KcUNj8+odwGJEqdWOHXxJi5y+W2K7qV6SraO6r/cIOUYYfY0MuhgXr9d0DchWZk9lFWvNCT7g1UPyBN4cAfeoqnk+s3vMaBaI9ZB4t2iFzqAfUQY4weCmXWVg3Bi77u76dQi7hgX/zaf89HIECdY0ft5fL4IY0EyzzpoNYsy1yBHL9TcnqSjlZKI8mJYT0bp9Ga7mvsQYEJYRHPFjSuSzgP2XR9Hor1ITNd3fA5m4ud1QMvAsWmJ784bM/sfGUutmfS1FdX8T2klzXnTcQnLEIzXb02IVXCArIXkW/0NvX0mUtqceW3XJsiuKhCZg+5I3Td87WFA/O4fmtpRMH2WoHFlAlzUAHHI5DorAltu77FXRl17zduhBl4LUVBAxCrCIGcDgwUcIEGMTfmOpJn7A6uhC8pk2xf6TvyBrOtxYh0TYYj1ywlAiWTB5IW9+xuzP0OvO4qA2E4WvEB6Yuu0zHE/AHXJyHcxqeKkg7ZLL/f8K9eq3c+mHKIE8W6M4ty4bsP7lhUAFf43nx4SO4aQpg3ZOIC4vVcVyJJfO0Ho75PuOsMDkTXCdL4MRmb2VjBhGzgXV7f7BOMnyNSnqb8Rf4=
  - secure: AZG2KnhJ7sUwKj9fYJYQkKrB2jgk0vE2ObwKR8siPwfv9pHhhgyKQH0pRbYipiU2+qI7RwebvagwhtLhmqxTXS+AatqSQD70KUJxzWLSdUGns+3L0+yKk3zOmeD7+lCMmp3FL+onytRVB+/tlUVuxmWbEMF2GfgqEJaDBjTd6DXafslIcy3vWYoQuGIrDTpk2EkVJl4PojnmRx8csiIpaN+Ot0N6wUYvdhB+c2A2+a9FvXKNPOsLcN61ogK8UYNP0nZdvphkn3IVi7DdIa0VdAnJeTlXwN2ES1lraCtp0pxQdfzIgCu8GzImedg12s80s9HDa6PYfHQ3QSdyLn8f0QPKBPGoJpwrwKY/51Q3+xFf89/Xg6Mwl1ATB93Kh9X4zPIsY/9wtk0XPTauSvYd3SoYrFQreFmCOAvAlnMK3lmBKl5kV0r2cfpzhSCZQLY4VuVNhbEnzX2eX+Tzg2R81/QLQ/ACH0VLSDjnCAXuYLTb13pOunS6ilWQN04j5sr25w2FfUWSey2H6up+24eQUPxxgYZSuzjRkr4KtxUvqwdA89Ct4sQfBv7ay4Xl+gikox72rCFuB9/mdnBkv30s+qeMVMg4jz8kB3LMJU+GRq32dZiLaVt3KWCYbik7DRnGFVi/HjSqjroTrhQEwUFgkDGshxrsYv8tLMCgNFhWt9k=
