language: node_js
node_js:
- 10.16.0
install: npm install
before_script: npm run dist
script: npm test
before_deploy: echo "All unit tests pass. Launching build on AWS EB."
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: sfr-front-end
  env: sfr-front-end-development
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: rnw-front-end-development
  on:
    repo: NYPL/sfr-bookfinder-front-end
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: DigitalResearchBooks-front-end
  env: digital-research-books-beta
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: DigitalResearchBooks-front-end
  on:
    repo: NYPL/sfr-bookfinder-front-end
    branch: beta-production
env:
  global:
  - secure: sBbLIPtXIpRUFo7PBduT8aQocYts2MTlBSKcCr/1WGGAoih3lEkTDPJkiGxaF6vqCCdfkBLPIECzYbiH49ZA6HrR/nnKVsvFbTAc5MQkCrPyipEXy27/urohzQDK1tH0wmr6Xz1Of80RwO4/viuX/pjRXwvbkw+jOO0+2J6JlLTxyNwhIn9m+id7Ja2sPB35ON+c/4X0r0bv4jMZGLg9IlC89N7q7UNdRXtpVeBTWJX//ZCEHGH1ZKqWOkC4GaWqXDDDFL75iRomkQ1akaYbFVWOVweLC1JmPXDgnhbbs7KB1kremausb/c1GhqQ1RMp5hsZCQ5ATP1pYlulo039/pRwSOGZ8so1q6KUefsU+X7RIsZ86vDU3mjIzI3URZjzUQlKo5CFdqWFULw0rOlBHPkgMLBtTgKBAe97Wx3wQBN3sm+yKoIP0GntLhCTxD4GEd1Bn7ccq+0WjGlzlLJYq1YnWoF9p/mHmWL49e6Vhn1U+MD143m4mGxUC1MYosBhm8EzT5x1vowleqvhOKmp3x3fXCfE98A/UfWyUHDBoFof2Bo5v+Y+wgAWX4+lDro0WpKZA/jPvOROnoiX8mwUS9xdOpoEu75lNg6LLcSBqjFPxcG0d5qK4uAdzpK15TS8cgfcttH2V3ZfPPPaBlSN8H+j2MfxuuvYMYca6ftSb4I=
  - secure: zcB+zqjBkv9Y2YHU3PgJ7xmWvL2q53g1zbZvmBVvLv0eEfqLr71Ca30oda0FsBLdQ0oXo4So0shBh5AME38x6KcUNj8+odwGJEqdWOHXxJi5y+W2K7qV6SraO6r/cIOUYYfY0MuhgXr9d0DchWZk9lFWvNCT7g1UPyBN4cAfeoqnk+s3vMaBaI9ZB4t2iFzqAfUQY4weCmXWVg3Bi77u76dQi7hgX/zaf89HIECdY0ft5fL4IY0EyzzpoNYsy1yBHL9TcnqSjlZKI8mJYT0bp9Ga7mvsQYEJYRHPFjSuSzgP2XR9Hor1ITNd3fA5m4ud1QMvAsWmJ784bM/sfGUutmfS1FdX8T2klzXnTcQnLEIzXb02IVXCArIXkW/0NvX0mUtqceW3XJsiuKhCZg+5I3Td87WFA/O4fmtpRMH2WoHFlAlzUAHHI5DorAltu77FXRl17zduhBl4LUVBAxCrCIGcDgwUcIEGMTfmOpJn7A6uhC8pk2xf6TvyBrOtxYh0TYYj1ywlAiWTB5IW9+xuzP0OvO4qA2E4WvEB6Yuu0zHE/AHXJyHcxqeKkg7ZLL/f8K9eq3c+mHKIE8W6M4ty4bsP7lhUAFf43nx4SO4aQpg3ZOIC4vVcVyJJfO0Ho75PuOsMDkTXCdL4MRmb2VjBhGzgXV7f7BOMnyNSnqb8Rf4=
  - secure: AZG2KnhJ7sUwKj9fYJYQkKrB2jgk0vE2ObwKR8siPwfv9pHhhgyKQH0pRbYipiU2+qI7RwebvagwhtLhmqxTXS+AatqSQD70KUJxzWLSdUGns+3L0+yKk3zOmeD7+lCMmp3FL+onytRVB+/tlUVuxmWbEMF2GfgqEJaDBjTd6DXafslIcy3vWYoQuGIrDTpk2EkVJl4PojnmRx8csiIpaN+Ot0N6wUYvdhB+c2A2+a9FvXKNPOsLcN61ogK8UYNP0nZdvphkn3IVi7DdIa0VdAnJeTlXwN2ES1lraCtp0pxQdfzIgCu8GzImedg12s80s9HDa6PYfHQ3QSdyLn8f0QPKBPGoJpwrwKY/51Q3+xFf89/Xg6Mwl1ATB93Kh9X4zPIsY/9wtk0XPTauSvYd3SoYrFQreFmCOAvAlnMK3lmBKl5kV0r2cfpzhSCZQLY4VuVNhbEnzX2eX+Tzg2R81/QLQ/ACH0VLSDjnCAXuYLTb13pOunS6ilWQN04j5sr25w2FfUWSey2H6up+24eQUPxxgYZSuzjRkr4KtxUvqwdA89Ct4sQfBv7ay4Xl+gikox72rCFuB9/mdnBkv30s+qeMVMg4jz8kB3LMJU+GRq32dZiLaVt3KWCYbik7DRnGFVi/HjSqjroTrhQEwUFgkDGshxrsYv8tLMCgNFhWt9k=
  - secure: 1N/Kmec5/9G/Opx0LZrA9ab9k0yaRW+cJz6C+mXwTsSTSy7n8jglkN6RZOwneQCihbtX4jmLEegqYaZQeRgsQXNVqdsM0GGQ/oEgEtMcWZVFI7uUAORCl7x/hUyPYxk8ffS0z3nR+5mSjWv+mBJCcbUbBSrPv+IsnMzTH3p5otwFO14Fg8hNCrbGh1b/g+9SDGEA9SZGLizXiIS8isWPeSdyaoLNbJ44FqiCUrgBZcFJTjJA4z1jXspG/fg/9Z9nVTrQLvHElw4OM5G5dQCaHyJY+Jj4HcU4Z3hc1AU8/kCcomhQIXoVo5tDEZQ3f9TGR1dS3NUkdj+S8ZtEOLRMLiPt1vDQTHVpEOJw3ce4cb+v6nbyZ8uYR7E5yNkY1gx/M7g2pZEvHBiMK/0XBs4Cy2w/8NOXmC/kY+ZPzADIs4OffAXjnK55lVUqUyZuWvg2gfXp+HTzlL5w7xTjgecf0N/Ysc+/yrgNO40n4D+EHC2wtkeM5xbDGSoSQH1shjWNzTha8LCYRWUROFKxbZbD2xF9F4VCohQ95sgxp8GrssjBUU3qNewopzP1V+l3Cgy+bOvtWsP9pU0q4BBUgHhHoyshVFX2Ubo03PxqvZHGFdU8lT+myPCKrTgZAo9SRhzezt4qHmlrwcCum7jnWmyfRrAhbcdrlZEAF73vJq71hD8=
  - secure: zo8DbYnsLTC9YlxEci/oOdxQ7mI6ihEtfdAfbE4mrJqG0rW0ZfkQMLyews0BmQJYJgfGviUV0Lava19h7ySQsSblvc+y+jSHy7bCq6WB9pS62O8zoaA23acbQIeMzivJrNGD/6Advx8wRm2WxbJ3hxFKh2F/ThlFSV3l990ZRGLGuJB94cSekL0N5AhZkWaVlxN75/4LOrJJtKct7+46HoH1ZB/P0frloRGh7FVnHVpIZI4TXlIesFcd4fbchHl1+3aA1Grzj2SYhTevB2WDU/Peq7scMbbJ5Qwwym+ZaliXTjO8DcW6TbXNb46BpqrS6EU8tOHuIWoacg0lpfTmcTwGbtY/MYb0mr83+K8SLt4S7jyPZZe+TwLZan7z6a1bN4yxfvoqTGIksN6sNECdg+nm1VxQ3zwi3uOdpWvvzbvtMPdq7GPVlFtn3AqbVSWqcqhEA4KPpkrFzDcna8B+i240GqXPVKMFL+GbIhWlKg+rdfj64mo5/tj62gSkE/CU/r/qb71No8+MJLouBQYMkG4TbBCgX27dV68j/EYis9iiMmqnqUUBJCR28Ab5rRy4EsQm4aYWvfqYDL0TLV1+bcSnwYK6sgQX6EQiWmX1fKrXRqdYDk8US+TuYVh/n3Xw6C72zIQmo1N3/hiJgrObYCqjP4/J32zI6N3xqCRDs4Y=
