version: "3"

services:
  web:
    container_name: sfr-bookfinder-front-end
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
