// Actions
export const Actions = {
  SEARCH: 'SEARCH',
  SEARCH_BY_KEYWORD: 'SEARCH_BY_KEYWORD',
  SEARCH_BY_TITLE: 'SEARCH_BY_TITLE',
  SEARCH_BY_AUTHOR: 'SEARCH_BY_AUTHOR',
  FILTER_RESULTS: 'FILTER_RESULTS',
  SORT_RESULTS: 'SORT_RESULTS',
};

export default Actions;
