name: Playwright Tests for Digital Research Books

on:
  schedule:
    - cron: "00 14 * * 1-5"
  pull_request:
    branches: [production]
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d
        working-directory: ./sfr-bookfinder-front-end

      - name: Update /etc/hosts
        run: |
          echo "127.0.0.1 local.nypl.org" | sudo tee -a /etc/hosts

      - name: Install Deps
        run: npm i @cucumber/cucumber@8.11.1 @playwright/test@1.29.1

      - name: Install Playwright Browser Utils
        run: npx playwright install --with-deps

      - name: Set the world parameters as an env var
        # WORLD_PARAMETERS set here will override anything set in cucumber.json
        run: |
          echo "WORLD_PARAMETERS={\"headless\": true}" >> $GITHUB_ENV

      - name: Run Cucumber tests
        run: npm run cucumber -- playwright/features --world-parameters '${{ env.WORLD_PARAMETERS }}'
        env:
          CATALOG_USERNAME: ${{ secrets.CATALOG_USERNAME }}
          CATALOG_USER_PIN: ${{ secrets.CATALOG_USER_PIN }}
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
          CUCUMBER_PUBLISH_ENABLED: true

      - name: Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: test_reports
          SLACK_MESSAGE: https://reports.cucumber.io/report-collections/01dbd6e8-653b-4597-b901-6caf2e653b07
          SLACK_TITLE: DRB Cucumber/Playwright Test Results
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: nyplorgBot
