name: Rspec Regression Testing

on:
  # will run on all PRs that are opened or updated (synchronized)
  pull_request:
    branches: [production, development]
    types: [opened, synchronize, reopened]

jobs:
  regression-test:
    name: Run rspec regression tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.0.0"]

    env:
      PA_TOKEN: ${{ secrets.CLONE_PAT }}
      BASE_URL: ${{ secrets.RSPEC_TEST_URL }}
      SEARCH_TERM: ${{ secrets.RSPEC_TEST_STRING }}
      TEST_DRIVER: ${{ secrets.RSPEC_TEST_DRIVER }}

    services:
      chrome:
        image: selenium/standalone-chrome

    steps:
      - name: Checkout rspec repo
        run: git clone https://$PA_TOKEN@github.com/nypl/rspec_researchNow.git

      - name: Run regression tests (prefixed with number code)
        run: bundle exec rspec -r ./spec/support/prod.rb --pattern spec/[12]?[0-9]*_spec.rb

