name: Rspec Regression Testing

on:
  # will run on all PRs that are opened or updated (synchronized)
  pull_request:
    branches: [production]
    types: [opened, synchronize, reopened]

jobs:
  regression-test:
    name: Run rspec regression tests
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2-beta
      with:
        # Private version of https://github.com/actions/hello-world-docker-action
        repository: USER/private-hello-world-docker-action
        ref: refs/tags/v1
        token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT to clone that private repo
    - name: Run the private action
      uses: ./
      with:
        who-to-greet: "Mona the Octocat"



        
    strategy:
      matrix:
        ruby-version: ["3.0.0"]

    env:
      PA_TOKEN: ${{ secrets.CLONE_PAT }}
      BASE_URL: ${{ secrets.RSPEC_TEST_URL }}
      SEARCH_TERM: ${{ secrets.RSPEC_TEST_STRING }}
      TEST_DRIVER: ${{ secrets.RSPEC_TEST_DRIVER }}
      CATALOG_USERNAME: ${{ secrets.CATALOG_USERNAME }}
      CATALOG_USER_PIN: ${{ secrets.CATALOG_USER_PIN }}

    services:
      chrome:
        image: selenium/standalone-chrome

    steps:
      - name: Checkout rspec repo
        run: git clone https://$PA_TOKEN@github.com/nypl/rspec_researchNow.git .

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run regression tests (prefixed with number code)
        run: bundle exec rspec -r ./spec/support/qa.rb --pattern spec/[12]?[0-9]*_spec.rb

